[tox]
envlist =
  py{311,312}-django{42}
  py{312,313,314}-django{52,60}
skip_missing_interpreters = true
extras =
  dev: dev

[gh-actions]
python =
  3.11: py311
  3.12: py312
  3.13: py313
  3.14: py314

[gh-actions:env]
DJANGO =
  4.2: django42
  5.2: django52
  6.0: django60

[testenv]
deps=
  django42: Django~=4.2
  django52: Django~=5.2
  django60: Django~=6.0
allowlist_externals =
  coverage
commands=
  - coverage run -m runtests
  - coverage xml
